### ISSUE TITLE
Application validation

### ISSUE THREAD

**Issue by AshKetchum07302016** [OfficeDev/Office-IT-Pro-Deployment-Scripts#159]
Hey people

First, thanks for the great tool you created! 
Now i got a problem, i can't launch the installation. If i generate the .xml file, i want to click on "Launch Installation", after it starts downloading and installing, i get this error message: 

PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1078.0 built by: NETFXREL3STAGE
	clr.dll 			: 4.6.1080.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: file:///C:/Users/username/Downloads/OfficeProPlusInstallGenerator.application
	Deployment Provider url		: http://officedev.github.io/Office-IT-Pro-Deployment-Scripts/OfficeProPlusInstallGenerator/OfficeProPlusInstallGenerator.application
						Server		: GitHub.com
	Application url			: http://officedev.github.io/Office-IT-Pro-Deployment-Scripts/OfficeProPlusInstallGenerator/Application%20Files/OfficeProPlusInstallGenerator_2_0_0_36/OfficeProPlusInstallGenerator.exe.manifest
						Server		: GitHub.com

IDENTITIES
	Deployment Identity		: OfficeProPlusInstallGenerator.application, Version=2.0.0.36, Culture=neutral, PublicKeyToken=7e4875a70752af6e, processorArchitecture=msil
	Application Identity		: Microsoft.CIE.Run.exe, Version=2.0.0.36, Culture=neutral, PublicKeyToken=7e4875a70752af6e, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.
	* Trust url parameter is set.
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\username\Downloads\OfficeProPlusInstallGenerator.application resulted in exception. Following failure messages were detected:
		+ File, OfficeInstallGenerator.dll, has a different computed hash than specified in manifest.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [07/09/2016 08:47:28] : Activation of C:\Users\username\Downloads\OfficeProPlusInstallGenerator.application has started.
	* [07/09/2016 08:47:28] : Processing of deployment manifest has successfully completed.
	* [07/09/2016 08:47:28] : Installation of the application has started.
	* [07/09/2016 08:47:28] : Processing of application manifest has successfully completed.
	* [07/09/2016 08:47:30] : Found compatible runtime version 4.0.30319.
	* [07/09/2016 08:47:30] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [07/09/2016 08:48:25] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, OfficeInstallGenerator.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

Could anybody help me ? 

Thanks in advance! 

Best regards, 
SBA

**Comment by AshKetchum07302016** [comment]
Found the problem.
It's necessary to have the actual build number.

**Comment by AshKetchum07302016** [comment]
Can get closed, thanks!
